services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - CONTAINER_PORT=${CONTAINER_PORT}
    ports:
      - "${DEV_PORT}:${CONTAINER_PORT}"
    volumes:
      - ${PWD}:/app

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - CONTAINER_PORT=${CONTAINER_PORT}
    ports:
      - "${PROD_PORT}:${CONTAINER_PORT}"

  db:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./docker/dbInit:/docker-entrypoint-initdb.d"
      - "mysql-data:/var/lib/mysql"

volumes:
  mysql-data:
