services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ${PWD}:/app

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:4000"
