services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - CONTAINER_PORT=${CONTAINER_PORT}
    ports:
      - "${DEV_PORT}:${CONTAINER_PORT}"
    volumes:
      - ${PWD}:/app

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - CONTAINER_PORT=${CONTAINER_PORT}
    ports:
      - "${PROD_PORT}:${CONTAINER_PORT}"
