# Build the Go binary
FROM golang:1.23.1 AS build-stage

ARG CONTAINER_PORT
WORKDIR /build
COPY go.mod go.sum ./
#RUN go mod download
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-X main.port=$CONTAINER_PORT" -o ./snippetbox ./cmd/web

# Copy the binary to a new image
FROM alpine:latest
WORKDIR /app
COPY --from=build-stage /build/snippetbox ./snippetbox
COPY --from=build-stage /build/ui ./ui

CMD ["/app/snippetbox"]
