# Build the Go binary
FROM golang:1.23.1 AS dev

RUN go install github.com/air-verse/air@latest

ARG CONTAINER_PORT
ENV CONTAINER_PORT=${CONTAINER_PORT}
WORKDIR /app
COPY go.mod go.sum ./
#RUN go mod download
COPY . ./

CMD ["air", "-c", ".air.toml"]